### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by cone56**
Upgrade package dependencies, specifically bumping `source-map` to 0.6.x - the latest version prior to a breaking API change.

### CODE REVIEW

**Comment by InakiAbete-Reflektion** [comment]
Tried your PR but I'm getting the same warning errors.
Did it work on your case?

**Comment by InakiAbete-Reflektion** [comment]
Nevermind, I was trying the wrong branch 🤦‍♂️ 
It works!

**Comment by cone56** [comment]
Good to hear it works!

Any chance of getting this merged and published @SlexAxton? It should also fix issue #116

**Comment by SlexAxton** [comment]
merged, patch version bumped, published.

Thanks friends!

**Pull request merged**
